apiVersion: v1
kind: Service
metadata:
    name: backend-service # Service Name
spec:
    type: ClusterIP # Service Type
    ports:
    - targetPort: 8000 # 1. Pod port: Port that you're allowing in the Pod
      port: 5000       # 2. Service port: Port that you're allowing in the Service
    selector:
        app: search-app
        type: backend