// Step 1: Create Action Types
export const UPDATE_AUTOCOMPLETE_OPTIONS = "UPDATE_AUTOCOMPLETE_OPTIONS";
export const UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";

